# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  api.<project-name>.development.com:
    site_hosts:
      - canonical: api.<project-name>.development.molamil.com
    local_path: ../../
    admin_email: signup@molamil.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    env:
      db_name: <db_name>
      db_user: <db_user>
