# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  production:
    site_hosts:
      - canonical: <production_url> #
      - canonical: <alt_production_url> #
    local_path: ../../
    repo: <project_repo> #
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
    env:
      wp_env: production
      db_name: <db_name> #
      db_user: <db_user> #
